import Head from 'next/head';
import Image from 'next/image';
import Gif from 'public/welcome.gif';

export default function Home() {
  return (
    <>
      <Head>
        <title>Discovering NextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-center pt-20 px-5 md:px-0'>
        <Image src={Gif} alt='my gif' className='rounded-lg' />
      </main>
    </>
  );
}
