import './globals.css';
import { FC } from 'react';
import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import Navbar from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Discovering NextJS',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang='en' data-theme='dark'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
