import './globals.css';
import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import Navbar from 'src/components/Navbar';

export const metadata: Metadata = {
  title: 'Discovering NextJS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' data-theme='dark'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
